MAGENTO2-148
shopgate/cart-integration-magento2-export pull request #1
Opened 2018-02-02 15:12 UTC by Skistims

added parent sku to the the internal order info

2018-02-05 08:24 UTC, augsteyer requested changes
also need to direct to 'develop' branch

2018-02-05 08:24 UTC, augsteyer commented on src/Model/Export/Product.php
> +        if (is_object($this->parent)) {
best if ```instanceof``` is used here. An instance that supports a call to ```getSku()``` and ```getTypeId()``` that is

2018-02-05 08:44 UTC, andre-kraus commented
Don't forget to update the CHANGELOG.md file as well.

2018-02-06 12:27 UTC, Skistims commented
@augsteyer done

2018-02-07 05:12 UTC, augsteyer approved these changes

2018-02-07 09:17 UTC, merged