Magento2 154 use new param requirements from parent function in base repo
shopgate/cart-integration-magento2-export pull request #4
Opened 2018-02-19 15:02 UTC by Skistims

2018-02-19 15:03 UTC, augsteyer commented
point to develop branch

2018-02-19 15:04 UTC, Skistims commented
yeah, sorry.

2018-02-19 15:08 UTC, augsteyer submitted a review, later dismissed

2018-02-20 09:17 UTC, augsteyer requested changes
```getReviews()``` need to be adjusted too

2018-02-21 14:07 UTC, augsteyer approved these changes

2018-02-21 15:27 UTC, merged