Magento2 722 relations
shopgate/cart-integration-magento2-export pull request #44
Opened 2020-07-29 14:07 UTC by sofib

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md

2020-07-30 07:42 UTC, Stereck requested changes
Just from gut feeling this adds much more complexity as expected, but I am not into the topic to judge if this can be simplified. However code in general looks fine except some CS adjustments that are needed to match project CS.

2020-07-30 07:42 UTC, Stereck commented on src/Model/Export/Product.php
> +
```suggestion
```

2020-07-30 07:42 UTC, Stereck commented on src/Model/Export/Product.php
> +    private function isProductTypeSupported($typeInstance)
Please always add PHP doc for at least methods that have parameters or return values.

2020-07-30 07:42 UTC, Stereck commented on src/Model/Export/Product.php
> +        if ($typeInstance instanceof Simple) {
No must have, but maybe a switch case would be easier to read here.

2020-07-30 07:42 UTC, Stereck commented on src/Model/Export/Product.php
> +        $result = [];
Please user alignment of = in this project.

2020-07-30 07:42 UTC, Stereck commented on src/Model/Export/Product.php
> +            $rows = $objectManager->create('Shopgate\Export\Model\ResourceModel\ConfigurableProduct')->getParentAndChildIdsByChildIds($relation->getUnprocessedRelationIds());
Can you please break those long lines?

2020-07-30 07:42 UTC, Stereck commented on src/Model/Export/Product.php
> +    private function isProductTypeSupported($typeInstance)
This method is a duplicate and seemingly never called.

2020-07-30 10:21 UTC, sofib commented on src/Model/Export/Product.php
> +        if ($typeInstance instanceof Simple) {
I think that's very individual - it is just 4 code paths here.

2020-07-30 10:21 UTC, sofib commented on src/Model/Export/Product.php
> +    private function isProductTypeSupported($typeInstance)
Right

2020-07-30 10:22 UTC, sofib commented on src/Model/Export/Product.php
> +            $rows = $objectManager->create('Shopgate\Export\Model\ResourceModel\ConfigurableProduct')->getParentAndChildIdsByChildIds($relation->getUnprocessedRelationIds());
yes

2020-07-30 10:38 UTC, sofib commented on src/Model/Export/Product.php
> +        $result = [];
Unfortunately we have no auto formatter for vs code or via ci. Done

2020-07-30 11:10 UTC, sofib commented
> Just from gut feeling this adds much more complexity as expected, but I am not into the topic to judge if this can be simplified. However code in general looks fine except some CS adjustments that are needed to match project CS.

There was an effort on reducing/limiting number of db queries that would otherwise happen if we'd query for each relation of a product separately. Export is already slowish but I still also can't be a judge of that.

2020-07-31 06:55 UTC, Stereck commented on src/Model/Export/Product.php
> +        $relatedProductIds = $relation->getRelatedProductIds();
```suggestion
        $crossSellIds      = $relation->getCrossSellIds();
        $upsellIds         = $relation->getUpsellIds();
        $relatedProductIds = $relation->getRelatedProductIds();
```

2020-07-31 06:55 UTC, Stereck commented on src/Model/Export/Product/Relation.php
> +        $classifierLookup = [];
```suggestion
        $relationIds      = [];
        $relationsLookup  = [];
        $classifierLookup = [];
```

2020-07-31 06:56 UTC, Stereck approved these changes

2020-07-31 10:06 UTC, merged